### ISSUE TITLE
Android/Raspberry Pi rendering bugs

### ISSUE THREAD

**Issue by loganmc10** [loganmc10/GLupeN64#13]
![screenshot_20160803-094616](https://cloud.githubusercontent.com/assets/848146/17372321/9d84ce0e-5960-11e6-8b91-2521c6470d32.png)

I don't get this behaviour on my laptop. If someone can tell by looking at that what might be wrong I'd appreciate it.

**Comment by loganmc10** [comment]
This is present even with the original GLSM code, so I'm not sure what is causing it, perhaps something else needs to be added to glsm_state_bind

**Comment by loganmc10** [comment]
I don't really see this in other games, and just the menus in Smash Bros are messed up, once you are "in-game" things look normal.

**Comment by loganmc10** [comment]
This seems to only happen sporadically now, and I saw it once on my Raspberry Pi after returning to the character selection screen after a match in Smash Bros

**Comment by loganmc10** [comment]
In addition, when I enabled GLES3 and Framebuffer Emulation, a whole other crop of graphical issues appear that I don't get on my laptop (Missing textures when LOD emulation is enabled in GoldenEye), flashing and missing textures in Pokemon Stadium.

**Comment by loganmc10** [comment]
The LOD issues in the GoldenEye menu are present on my laptop as well

**Comment by loganmc10** [comment]
These are the 2 lines that are causing the LOD issues (but it works in regular mupen64plus)

https://github.com/gonetz/GLideN64/blob/4bcf330759f71a9879dd2888e349238bd6e9c39c/src/Textures.cpp#L1068-L1069

**Comment by loganmc10** [comment]
I also see something similar in Mario Party 2.

**Comment by gizmo98** [comment]
Did you tried nativeResFactor=1? I have not seen the ssb glitch and mario party looked better with nativeResFactor=1.

**Comment by loganmc10** [comment]
Ya I need to play around a bit more, I briefly tested on my phone at 640x480 and the problem went away, but it was there at 320x240, very strange. (this is with Framebuffer Emulation disabled)

**Comment by loganmc10** [comment]
It's just strange that the resolution seems to make a difference for a few of the textures, but not all of them, and that this seems to affect this port, but not standalone mupen64plus, and it doesn't seem to affect my laptop running the plugin in GLES2, but it affects android and rpi.

**Comment by gizmo98** [comment]
NEON opt or ARM related stuff?

**Comment by loganmc10** [comment]
I've tried it without NEON_OPT and VEC4_OPT, same issue. This one is really stumping me...

**Comment by loganmc10** [comment]
Pretty much the only way I can think of to solve this problem:

Install apitrace on a Raspberry Pi, using apitrace to capture some frames in Mario Party when the glitch is happening.

Do the same thing on a laptop running the plugin in GLES2 mode, and then compare the apitrace's line by line to figure out how they are different.

One day I'll probably get around to that...

**Comment by LEGOAnimal22** [comment]
I don't know if this is exactly like your problem, but I experience this in Banjo-Kazooie on 320x240:

![retroarch-0814-195906](https://cloud.githubusercontent.com/assets/4968240/17654000/30e36932-625b-11e6-9494-7f60eb8f8c3e.png)

640x480 and above do not show this behavior.

**Comment by loganmc10** [comment]
Here is another one, on my Nexus 4, using GLES3 mode, everything is black and white and messed up:

![screenshot_2016-08-22-21-05-51](https://cloud.githubusercontent.com/assets/848146/17879256/b1fd8860-68ad-11e6-87e7-b35400af9209.png)

But it all looks normal on GLES2 mode

**Comment by loganmc10** [comment]
I think I finally figured this out, I believe setting

```
glPixelStorei(GL_UNPACK_ALIGNMENT,1);
```

solves this problem, but I need to do some testing to see if it is really gone for good, and if that setting will break anything else.
