### ISSUE TITLE
Rendering bug

### ISSUE THREAD

**Issue by loganmc10** [loganmc10/GLupeN64#2]
![snapshot](https://cloud.githubusercontent.com/assets/848146/16168923/6744da6c-34d7-11e6-8508-ef2304a904a4.png)

Some games work great (Super Mario, Mario Kart), and some games having graphical bugs like this picture (Smash Bros, GoldenEye), the games really crawl as well, whereas the games that look good run smoothly

**Comment by mudlord** [comment]
Noticed in the original mupen64plus-libretro gliden64 port, there is a similar issue with LoZ: OoT's intro. The fire effect would be completely opaque with no alpha. Might be a blender/combiner/shader problem with that regard, not sure what the problem is here.

**Comment by loganmc10** [comment]
Ya almost every game has some sort of bug, OOT worked fine during the opening cut scenes, but as soon as the "gameplay" started, it looked like this:

![snapshot](https://cloud.githubusercontent.com/assets/848146/16175270/ae140e64-35a3-11e6-961b-8c00b75e6e40.png)

It doesn't do that in standalone mupen64plus, so it is definitely something up with libretro.

I assume there is some important information that is not being passed to [glsm_state_bind](https://github.com/libretro/libretro-common/blob/master/glsm/glsm.c#L1893)

**Comment by mudlord** [comment]
I thought gliden64 had its own state machine :o

**Comment by loganmc10** [comment]
Ya but it doesn't render to the correct framebuffer, using the libretro glsm stuff is what allowed the video to work (without modifying the GLideN64 code too much, it just needed some change to OpenGL.h)

**Comment by dankcushions** [comment]
@loganmc10 did you get any further with this? I'm really excited about this project :)

I know this stuff isn't so important, but I'm familiar enough with libretro to attempt to expose all the various gliden64 ini options as core options, if that would be useful?

**Comment by loganmc10** [comment]
I haven't worked on this lately, this rendering issue is kind of a show stopper. It's either an issue with FBOs or with glsm (the libretro state machine), I might look into it a bit later in the week, but I wasn't planning on working on this much until this rendering stuff is figured out.

Once that is working i would love the help with the core options

**Comment by loganmc10** [comment]
I'm pretty much out of ideas on this, I've tried a number of different things without any success.

**Comment by loganmc10** [comment]
I'm quite interested in getting this working, I'll put a $50 USD "bounty" on this bug for whoever can get this working properly.

**Comment by loganmc10** [comment]
I finalllllly figured this out.

glVertexAttribPointer needs to be dealt with in glsm_state_bind

I'll work on this over the next few days to get it all working properly

**Comment by loganmc10** [comment]
@dankcushions This should be fixed with the latest commit, I've tested it on x64 Linux and the Raspberry Pi, feel free to test it out if you'd like.

I've still got some work to do to optimise the libretro GL code, but at least it is rendering properly now.

If you'd like to help out implementing the core options or anything else just let me know and I can give you some help getting started.

**Comment by dankcushions** [comment]
that's great! well done! i'd love to help out when i have a moment. i'll try and test it soon.
