### ISSUE TITLE
Banjo-Tooie: "No Controller" Message

### ISSUE THREAD

**Issue by LEGOAnimal22** [loganmc10/GLupeN64#23]
The libretro version of mupen64plus also had an issue with this a couple years ago.
Reference: https://github.com/libretro/mupen64plus-libretro/issues/24

LEGOAnimal22

**Comment by loganmc10** [comment]
Thanks, this looks like a problem that will have to be fixed upstream (mupen64plus). I'll look at this tomorrow.

If you are able, you can try making this change:
https://github.com/libretro/mupen64plus-libretro/commit/d21669636cbd0cb7656375db487c2951e10e0a11

Inside the "mupen64plus-core" folder, that would confirm if this patch needs to be submitted to mupen64plus

**Comment by LEGOAnimal22** [comment]
I'll take a stab at that tomorrow :smiley:

**Comment by LEGOAnimal22** [comment]
Submitted fix in https://github.com/mupen64plus/mupen64plus-core/pull/176

**Comment by loganmc10** [comment]
I see they didn't like the patch. The current mupen64plus-libretro rom.c doesn't seem to have this fix, do you know why it works for them and not for GLupeN64?

**Comment by loganmc10** [comment]
Also, do you get this message with standalone mupen64plus?

**Comment by LEGOAnimal22** [comment]
Just tried it with standalone, no message appeared. As for why it does not work for this project, I have no idea.

**Comment by loganmc10** [comment]
Ok, I'd rather fix this a "proper" way.

I believe this is probably happening because this line (romdatabase_open)
https://github.com/mupen64plus/mupen64plus-core/blob/master/src/api/frontend.c#L94-L95

Is not included in the libretro code (in this plugin or mupen64plus-libretro)

It is not included because it tries to read "mupen64plus.ini"
https://github.com/mupen64plus/mupen64plus-core/blob/master/data/mupen64plus.ini

Which is where it gets all the game specific parameters from.

This becomes tricky, typically libretro cores are just a .so file, no extras. So either I will somehow have to "bake" this .ini file into the shared library, or people will need to install the .ini file along with the .so file (which is not common for libretro cores).

I'm leaning towards somehow baking the information in the .ini into the core. I would be especially happy if it could somehow read that file and do it during the build process, so that I don't have to maintain a separate copy of that file in the code.

**Comment by loganmc10** [comment]
Ok I just commited https://github.com/loganmc10/GLupeN64/commit/84720a412c71a840d3dfdf119a92c8a32fd9595a

That will allow you to take a copy of mupen64plus.ini (located in mupen64plus-core/data), and put it in the directory that you launch GLupeN64 from.

Remember, it is going to look in your current directory, not necessarily the directory where the .so file is located. Let me know if that fixes the problem.

**Comment by dankcushions** [comment]
@loganmc10 i'm being pedantic here, and i'm not sure it will fit in your core, but if you can be bothered i would suggest using RETRO_ENVIRONMENT_GET_SYSTEM_DIRECTORY for any files needed (with the current directory as a fallback maybe). RETRO_ENVIRONMENT_GET_SAVE_DIRECTORY is good for saves and anything user-generated.

eg: https://github.com/libretro/mame2003-libretro/blob/fda911a31ecd8648bcb161e5e395edc795a306bc/src/libretro/libretro.c#L393

**Comment by loganmc10** [comment]
That's a good point, that is a much better place to look for it.

**Comment by loganmc10** [comment]
@dankcushions I've updated it https://github.com/loganmc10/GLupeN64/commit/0ac376626898e89bc557523887efcad7ad96de00

Now it will search the retroarch system dir, then your current directory, then a few pre-defined directories, so if you have mupen64plus installed on the same system, it will "magically" find that file.

**Comment by LEGOAnimal22** [comment]
@loganmc10 It seems like most of "mupen64plus.ini" is the name, CRC, and MD5 of the rom. The CRC's and MD5 are only used for looking up ROM settings, and the name can be pulled from the ROM header.

What I'm trying to say is that you could shorten the file down to only include the entries that have patches, e.g. "Savetype=SRAM" or "Players=2".

**Comment by loganmc10** [comment]
I'd rather keep it working the way it works in mupen64plus, does reading the .ini file with the latest commits solve the Banjo Tooie problem?

**Comment by LEGOAnimal22** [comment]
Updated to the latest commit, yes, the Banjo-Tooie problem is solved.

**Comment by LEGOAnimal22** [comment]
@loganmc10 I shortened down mupen64plus here if you want to take a look: https://gist.github.com/LEGOAnimal22/270bcbeb806b13713595c5c358e0ee6e
I took out about 10,200 lines.

**Comment by loganmc10** [comment]
I totally agree, no point having such a huge file if it isn't going to make any difference. But that is something that should be submitted to mupen64plus-core if they will take it.

I think I'm happy with how it is now, it reads mupen64plus.ini just like mupen64plus does. I'll add a bit of an explanation to README.md about the .ini file and then marked this as solved.

**Comment by loganmc10** [comment]
@LEGOAnimal22 Just FYI I've just added a commit that bakes in the mupen64plus.ini, so it won't need to read the file anymore:

598b441e3844af4841df25f48f35ef09fe97d621

**Comment by LEGOAnimal22** [comment]
Yay! Thanks for letting me know :)
