### ISSUE TITLE
RetroArch shaders might not work

### ISSUE THREAD

**Issue by loganmc10** [loganmc10/GLupeN64#27]
I hear that RetroArch shaders cause a black screen when they are enabled. It could be because of the changes I've made to glsm

**Comment by loganmc10** [comment]
I tried out a few shaders and they seemed to work fine actually. I came across one in the "mudlord" folder that caused a black screen, but I hear they are hit and miss anyway?

I'd love it if someone else could try out RetroArch shaders when they get a chance.

**Comment by orbea** [comment]
I have several shaders with your glsm patched into mupen64plus-libretro and I could not find that was broken after the changes. Like you said I found one in mudlord's folder that was broken before and after the changes.

However as I do not normally use shaders I could of easily missed the one that was broken.

**Comment by loganmc10** [comment]
Ok, well I'll close this until someone can come up with a reproducible example
