### ISSUE TITLE
Integrate GLSL Optimizer

### ISSUE THREAD

**Issue by loganmc10** [loganmc10/GLupeN64#28]
Similar to what I was playing around with here:
https://github.com/loganmc10/GLideN64/commit/23ad5b507d9c16b462166e56467d25d522446487

This is the project that will be integrated:
https://github.com/aras-p/glsl-optimizer

It may provide a performance boost on some GLES devices, probably won't make much of a difference on the desktop.

**Comment by dankcushions** [comment]
I think I mentioned this before but I'm interested in getting the optimizer as a library integrated into  retroarch so it can be used for other tasks (eg to optimize GLSL screen shaders - got some good results here: http://libretro.com/forums/showthread.php?t=6259 ).

Libretro might not be too keen in getting a C++ library included into Retroarch, but maybe as an optional submodule? It would be cool to kill two birds with this one, but either way this will be a good use-case :)

**Comment by loganmc10** [comment]
I totally agree, in fact the benefits there would probably be huge, since
most of those shaders are converted from CG instead of being hand written.

I don't see what the problem is with mixing C and C++, this project does
(mupen64plus is C and GLideN64 is C++), but they don't like it I guess.

Anyway the scope of work to get this working here is fairly low, I'll
probably have it done tomorrow. RetroArch is a whole other beast, not to
mention all the arguing that would accompany the coding work.

**Comment by dankcushions** [comment]
I agree with all that. I suspect if it's a compartmentalised, optional submodule library with a C interface then there wouldn't be a problem. There is C++ stuff already in RetroArch for a few other things (eg glslang).

https://github.com/libretro/RetroArch/blob/master/CONTRIBUTING.md#non-obvious-things (not sure what to make of that.. maybe C++ is ok after all?)

But like you say, one for another day :)

**Comment by loganmc10** [comment]
Done, it is enabled for GLES devices, not for desktops.
