### ISSUE TITLE
Build Failure -  undefined reference to `glcpp_parser_parse'

### ISSUE THREAD

**Issue by orbea** [loganmc10/GLupeN64#29]
OS: `Slackware64-current`

```
./glsl-optimizer/src/glsl/glcpp/pp.o: In function `glcpp_preprocess':
pp.c:(.text+0x25d): undefined reference to `glcpp_parser_parse'
./glsl-optimizer/src/glsl/glcpp/glcpp-parse.o: In function `yyparse':
glcpp-parse.c:(.text+0x3086): undefined reference to `yylex'
collect2: error: ld returned 1 exit status
Makefile:368: recipe for target 'glupen64_libretro.so' failed
make: *** [glupen64_libretro.so] Error 
```

**Comment by loganmc10** [comment]
You might need "bison" installed now. Can you try that? If that's the case I'll update the building instructions

**Comment by orbea** [comment]
`bison-3.0.4-x86_64-1` Is installed.

**Comment by orbea** [comment]
Running this script in `glsl-optimizer` works around it.

https://github.com/bkaradzic/bgfx/blob/master/3rdparty/glsl-optimizer/generateParsers.sh
```
#! /bin/sh
flex --nounistd -osrc/glsl/glcpp/glcpp-lex.c src/glsl/glcpp/glcpp-lex.l
flex --nounistd -osrc/glsl/glsl_lexer.cpp src/glsl/glsl_lexer.ll
bison -v -o "src/glsl/glcpp/glcpp-parse.c" -p "glcpp_parser_" --defines=src/glsl/glcpp/glcpp-parse.h src/glsl/glcpp/glcpp-parse.y
bison -v -o "src/glsl/glsl_parser.cpp" -p "_mesa_glsl_" --defines=src/glsl/glsl_parser.h src/glsl/glsl_parser.yy
```

**Comment by loganmc10** [comment]
Ok thanks, I ran that script and committed the result https://github.com/loganmc10/GLupeN64/commit/c73040afb36671538097266a726b8d292689586f

The GLSL optimizer isn't actually used on the desktop anyway, so I also modified the makefile to not even build it unless you are compiling for OpenGL ES

**Comment by orbea** [comment]
I can confirm this is fixed, thanks!
