### ISSUE TITLE
enableNativeResTexrects causes graphical glitches

### ISSUE THREAD

**Issue by orbea** [loganmc10/GLupeN64#32]
![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/Legend%20of%20Zelda,%20The%20-%20Majora's%20Mask%20%28U%29%20[!]-160827-111949.png)
![2](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/Legend%20of%20Zelda,%20The%20-%20Majora's%20Mask%20%28U%29%20[!]-160827-110934.png)
![3](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/Legend%20of%20Zelda,%20The%20-%20Majora's%20Mask%20%28U%29%20[!]-160827-111012.png)
![4](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/Legend%20of%20Zelda,%20The%20-%20Majora's%20Mask%20%28U%29%20[!]-160827-111032.png)

**Comment by loganmc10** [comment]
Is this new? Can you try it from this commit:

**Comment by orbea** [comment]
When trying that commit its both better and worse.

enableNativeResTexrects
![4](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/Legend%20of%20Zelda,%20The%20-%20Majora's%20Mask%20%28U%29%20[!]-160827-113837.png)

Without
![5](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/Legend%20of%20Zelda,%20The%20-%20Majora's%20Mask%20%28U%29%20[!]-160827-113935.png)

**Comment by orbea** [comment]
I don't really consider this a high priority issue, I just wanted to make sure it was known.

**Comment by loganmc10** [comment]
Ok should be fixed in the latest commit, when I enable native res texrects, the colors get all messed up. I believe that is what you were experiencing in your 2nd screenshot? I think I experience this in mupen64plus as well, but I'll have to test

**Comment by orbea** [comment]
That broke the menu.
![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/2016-08-29-101216_1680x1050_scrot.png)

**Comment by loganmc10** [comment]
Whoops, fixed now:
https://github.com/loganmc10/GLupeN64/commit/bb7302118ab488b07ec8599b5629efbf1486b34b

**Comment by orbea** [comment]
Thanks, the menu and the initial issue are solved. It looks like the screenshot with incorrect colors, if that is the same as mupen64plus then it should be fixed upstream.

**Comment by loganmc10** [comment]
ya I'll test it with mupen64plus in a bit, I haven't seen anyone else complain about that, but I seem to remember getting that with mupen64plus, everything looks yellow.

**Comment by orbea** [comment]
There are a lot of little issues beyond that with that setting.

Examples:
![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/mupen64plus/2016-08-06-153722_1680x1050_scrot.png)
![2](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/2016-08-29-102636_1680x1050_scrot.png)
(When starting a game from the RA menu only)

**Comment by loganmc10** [comment]
You mean starting a game from the RetroArch menu when EnableNativeResTexrects is enabled? It seems to work ok for me, what game are you launching?

**Comment by orbea** [comment]
Yes, all of the above images are with Majora's Mask. I am loading a game from the history tab to be exact, it does not happen when trying to do so from the terminal.

**Comment by loganmc10** [comment]
Is the blue box consistently there? Like is the image permanently messed up, or it goes away? And it only happens with EnableNativeResTexrects? Sorry I'm just trying to reproduce the issue.

**Comment by orbea** [comment]
It happens every time, but for a moment before the game starts and it can be another color than blue.

**Comment by loganmc10** [comment]
I still can't seem to reproduce that issue, but I did reproduce the color issue on mupen64plus, I opened an upstream issue:

https://github.com/gonetz/GLideN64/issues/1102

**Comment by orbea** [comment]
I can no longer reproduce the flash of colors for some reason...

I can reproduce the first example however and also noticed that the Majaro's Mask logo does not render with EnableNativeResTexrects. Can you reproduce that as well?

Here is an apitrace which shows the issues here, does it help?
http://ks392457.kimsufi.com/orbea/stuff/trace/libretro/glupen64-majaro.trace.xz

**Comment by loganmc10** [comment]
When you say "the Majaro's Mask logo", what do you mean? I see the N64 logo and the spinning mask when I start the game.

**Comment by loganmc10** [comment]
The current version of GLupeN64 no longer needs MESA_GL_VERSION_OVERRIDE or MESA_GLSL_VERSION_OVERRIDE set, you might want to unset those if you have them set, they might be screwing things up?

**Comment by orbea** [comment]
I don't have those set, I only ever set them for the specific environment that was starting GLupeN64.

I mean this logo, which will not render properly with EnableNativeResTexrects.
![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/Legend%20of%20Zelda,%20The%20-%20Majora's%20Mask%20%28U%29%20[!]-160829-122443.png)

**Comment by loganmc10** [comment]
Ok I've got it, it basically looks like this without ever changing?
![zelda_majora s_mask-000](https://cloud.githubusercontent.com/assets/848146/18064426/976f567e-6dec-11e6-8185-b34534abde3f.png)

That screenshot was taken on mupen64plus, it is reproducable there as well.

**Comment by orbea** [comment]
So its another upstream issue, how about this one. A driver issue? Does my apitrace show it for you? It blackscreens on my thinkpad t420...
![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/mupen64plus/2016-08-06-153722_1680x1050_scrot.png)

**Comment by loganmc10** [comment]
The apitrace seems to play ok (minus the Zelda logo issue), it ends right where Link is "in game" basically. At what point does it black screen? I can't really tell what the image is from.

**Comment by loganmc10** [comment]
Actually nevermind, you mean right after you hit "load game"? It is supposed to be displaying some text explaining the backstory right?

Ya that is also missing on mupen64plus, it shows up properly with enableNativeResTexrects disabled.

I actually haven't ever played Majora's Mask so I'm not very familiar with how it is supposed to go.

**Comment by orbea** [comment]
This is from right before the above logo / title screen.

**Comment by loganmc10** [comment]
It seems like the whole thing is pretty screwed up, the guy that does mupen64plus Android edition confirmed that he sees issues as well, so it's probably all related.

**Comment by loganmc10** [comment]
So it seems like this is pretty much fixed, the rest of this is upstream issues, and the black screen now has its own issue, ok to close?

**Comment by orbea** [comment]
Tthanks.
