### ISSUE TITLE
Majora's Mask: Black screen with thinkpad t420.

### ISSUE THREAD

**Issue by orbea** [loganmc10/GLupeN64#33]
On my older thinkpad t420 with an arch install I get a black screen, unfortunately I am not set up to do much debugging. Other games like Kirby 64 seem to work fine.
```
OpenGL core profile version string: 3.3 (Core Profile) Mesa 11.1.2
```
gliden64.log
```
N64 depth compare and depth based fog will not work without Image Textures support provided in OpenGL >= 4.3 or GLES >= 3.1
```

**Comment by loganmc10** [comment]
Can you compile with DEBUG=1 in the Makefile and let me know if there is any extra console or gliden64.log output?

Also, this works on other devices for you correct? Just not the t420?

**Comment by orbea** [comment]
I did and there wasn't anything extra. I suspect I will need a debug mesa on my arch, but that will take some doing. My guess is that something wants opengl 4.3 or newer which my desktop provides, but my laptop doesn't.

**Comment by loganmc10** [comment]
I don't think OpenGL 4.3 will help, the core requests an OpenGL 3.3 core context. I do my testing inside VirtualBox using Mesa + llvmpipe (when I don't have access to my regular machine), which only provides OpenGL 3.3 and it seems to render fine.

At home I have a t520 that is running Fedora (Intel Graphics, the Nvidia card is disabled), I'll test Majora's Mask on it tonight.

**Comment by orbea** [comment]
My thinkpad has intel graphics, might be only an intel issue? I will try updating my mesa later at least.

**Comment by loganmc10** [comment]
Ya I would try updating Mesa, both the machines I am testing on have Mesa 12 so I'm not sure if that could be the difference.

I know there have been Mesa Intel issues in the past, this comes to mind:
https://github.com/gonetz/GLideN64/issues/970#issuecomment-214977997

You could try enabling EnableLegacyBlending (Faster but less accurate blending mode), but an update to Mesa might fix it as well.

**Comment by orbea** [comment]
`EnableLegacyBlending` gets past the black screen.

**Comment by loganmc10** [comment]
Ya so I'm assuming an update to Mesa would also fix the issue. I think older versions of Mesa (at least for Intel) had an issue with the new blending code that gonetz wrote

**Comment by orbea** [comment]
mesa-12.0.1 solved it, I will close this. Thanks.
