### ISSUE TITLE
Segmentation fault when toggling full screen.

### ISSUE THREAD

**Issue by orbea** [loganmc10/GLupeN64#34]
OS: `Slackware64-current`
`RetroArch-2016.09.01_fd7949c_master-x86_64-1_git`
`GLupeN64-2016.09.01_471d95c_master-x86_64-1_git`

When toggling full screen with the `f` key GLupeN64 will segfault, unfortunately the backtrace will result in a corrupt stack, mupen64plus-libretro will do this as well.
https://github.com/libretro/mupen64plus-libretro/issues/332
```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x00007ffff1d470e9 in __memcpy_sse2_unaligned () from /usr/lib64/debug/libc.so.6
```
Full gdb log: http://pastebin.com/jVcL1h2G

**Comment by loganmc10** [comment]
When you say "mupen64plus-libretro will do this as well", do you mean the corrupt stack, or the segfault when toggling full screen? Does full screen toggling work in mupen64plus-libretro?

**Comment by loganmc10** [comment]
It looks like mupen64plus-libretro doesn't have this problem

**Comment by loganmc10** [comment]
I'm not too familiar with RetroArch, do you know what code actually execute inside RetroArch when fullscreen is toggled? Then I could see what is happening.

**Comment by orbea** [comment]
Sorry, my phrasing was lacking. Mupen64plus-libretro does not have this problem, but it does have a problem with corrupt stacks when trying to use gdb.

**Comment by loganmc10** [comment]
I believe this can likely be solved by calling PluginAPI::ChangeWindow() if fullscreen is toggled. mupen64plus has a mechanism to notify the graphics plugin if the user changes the video mode (M64VIDEO_FULLSCREEN, M64VIDEO_WINDOWED), but I'm not aware of any mechanism for RetroArch to notify the core that fullscreen has been toggled.

I might have to wade my way into the IRC channel to see if there is some mechanism for that.

**Comment by loganmc10** [comment]
Ok should be fixed in a93cbe0ac9874fabb721610e7e25740b8237b7ec

**Comment by orbea** [comment]
Yes, thanks!

**Comment by loganmc10** [comment]
Thanks for doing all this testing by the way. It's very helpful to have someone else trying things out that I might not otherwise test.
