### ISSUE TITLE
How to acquire this core for RetroArch (Windows) [REQUEST]

### ISSUE THREAD

**Issue by SigmaVirus** [loganmc10/GLupeN64#36]
I would really like to try this core out but I can't seem for the life of me find a compiled downloadable version anywhere.

Would it be OK to make a request as I'm in a position where I can't compile this myself.

Thanks in advance!

**Comment by loganmc10** [comment]
This is sort of a duplicate of #3 . There is no Windows build, I don't have a Windows system so I can't build or test it there. There will almost certainly need to be some code changes for this to work on Windows.

If anyone is willing to do it I'll happily accept a pull request

**Comment by SigmaVirus** [comment]
Thanks logan.

This is a interesting and exciting project that have much potential and I have seen you contribute to GLideN64 a lot.

I'm eagerly awaiting to see if it's possible to compile for Windows users.

**Comment by loganmc10** [comment]
hi @SigmaVirus , I've compiled a version for Windows, can you try it out for me?

https://s3.amazonaws.com/loganbuildbot/glupen64_libretro.dll

**Comment by loganmc10** [comment]
@orbea if you have a Windows machine and are able to test it out that'd be helpful as well. It seems to work normally for me on Windows 7 x64

**Comment by orbea** [comment]
Nope, I can't test with windows as I haven't had windows since vista.

**Comment by SigmaVirus** [comment]
Thanks a lot logan, will try this out tonight as soon as I get home from work!

**Comment by Tatsuya79** [comment]
Thanks but it's not working for me on win7 x64 Nvidia 770 GTX:
http://pastebin.com/YSKm2pkd

**Comment by loganmc10** [comment]
Can you give any output from when it crashed with no shader?

**Comment by loganmc10** [comment]
Also can you try the released version of 1.3.6 instead of a nightly and let me know if it is any different?

**Comment by loganmc10** [comment]
Ok so is it fair to say that the Windows build is working then? Are there any obvious bugs to sort out or can I close this issue?

**Comment by Tatsuya79** [comment]
Well, the bug is that it's crashing with cg shaders.
It's crashing with the exact same one I'm using with mupen64+ in retroarch.

**Comment by loganmc10** [comment]
Ok I'll look into that, I'm almost 100% sure that it's a RetroArch issue (because of the way this core requests an OpenGL context) but I'll look into it.

**Comment by SigmaVirus** [comment]
OK, I'm back with a report.

First off, THANK YOU logan!!!

Judging by the above comment you can probably guess that it worked straight out the box with shaders and all (I'm on Windows 10 Anniversary Update RS1 BTW)

These games worked beautifully with minor glitches:

007 - GoldenEeye (Europe) NOTE: OK
DOOM 64 (Europe) NOTE: OK
Legend of Zelda, The - Majora's Mask (Europe) NOTE: OK, although slow with both dynamic_recompiler and cached_interpreter
Legend of Zelda, The - Ocarina of Time - Master Quest (Europe) NOTE: OK
Legend of Zelda, The - Ocarina of Time (Europe) NOTE: OK
Mario Kart 64 (Europe) NOTE: OK
Paper Mario (Europe) NOTE: OK, only minor glitches in start menu the little I tested it
Perfect Dark (Europe) NOTE: Didn't boot with cached_interpreter at all but worked with dynamic_recompiler
Star Wars - Shadows of the Empire (Europe) NOTE: OK
Super Mario 64 (Europe) NOTE: OK
Super Smash Bros (Europe) NOTE: OK

However there were some issues:
Yoshi's Story (Europe) NOTE: After Yoshi says Nintendo everything goes black screen, this is with both dynamic_recompiler and cached_interpreter tested.
Not sure why the game don't want to work when it works in the stand-alone emulators.

And finally, going fullscreen results in crashes and this is tested with shaders on and off, don't know why this happens.

Otherwise great work!

**Comment by loganmc10** [comment]
does Yoshi's Story work with mupen64plus+GLideN64 in Windows?

I can confirm the full screen crash. I'm not really a Windows guy so I don't really know how to debug that, on Linux I would use gdb but I don't know how to sort that out on Windows (fullscreen works in Linux).

**Comment by SigmaVirus** [comment]
Last time I tested mupen64plus+GLideN64 Yoshi's Story was playable.
I'll have to verify that again though because it's been a while since I even used mupen64plus.

Could be my settings too, I don't know. I'll have to try this out more thoroughly.

**Comment by SigmaVirus** [comment]
BTW I noticed while reading through this issue that Tatsuya79 had problems with crashes regarding cg shaders.

FWIW I can use my cg shaders just fine without crashes. I'm using a homemade S-video shader and my GPU is a AMD R9 380X card.

So cg shaders isn't completely broken.

**Comment by loganmc10** [comment]
Ya it's more a RetroArch issue, I filed an issue with them: https://github.com/libretro/RetroArch/issues/3545 but it doesn't look like they'll fix it.

**Comment by SigmaVirus** [comment]
Well this specific request have been fulfilled and various preliminary status reports have been given with positive results.

The plugin works, let's take specific issues in separate issue reports from here on out.

I'm closing this issue now.

**Comment by loganmc10** [comment]
By the way, the latest Windows build can always be found here now:

http://loganbuildbot.s3-website-us-east-1.amazonaws.com/

**Comment by twinaphex** [comment]
@loganmc10 I added glupen64 to the libretro buildbot for Linux so far, I think Windows and Android have yet to be added.

Good job with Glupen64 BTW, I was pleasantly surprised when running it, it's still a lot slower than Glide64, a lot more framedrops (and I definitely hated the forced frameskip that I saw in Killer Instinct gold, which doesn't happen with mupen64plus libretro with Glide64), but overall there are some things Gliden64 does better than Glide64 at least.  Not everything though but some games are definitely rendered better.

You want to help us getting the remaining cores for the other platforms (Windows/Android) on the libretro buildbot as well? I think it would just make it more convenient for everybody involved.

**Comment by loganmc10** [comment]
@twinaphex thanks, I'll have to chat with you sometime over IRC about getting this setup on the libretro buildbot. For Windows cores, do you typically compile them on Windows with Visual Studio, or from Linux using mingw or something?

Right now I have a buildbot setup for this repo using Travis CI, it compiles for Linux, Windows, Android, and Raspberry Pi, all from Ubuntu 16.04, so I'm sure it's possible to get it setup with your buildbot.

**Comment by twinaphex** [comment]
About Windows - from Linux using mingw.
