### ISSUE TITLE
Zelda: Orcarina of Time: Pause screen spawns slowly.

### ISSUE THREAD

**Issue by orbea** [loganmc10/GLupeN64#37]
I've noticed an interesting behavior where with GLupeN64 the pause screen in Orcarina of Time takes ~6 seconds to appear, but does so almost instantly in mupen64plus-libretro. Do you have any idea why there is such a slowdown?

**Comment by loganmc10** [comment]
I'll have to test this vs mupen64plus+GLideN64 to see if it is any different. I know that it is slow, but I'll check if it is any slower thsn upstream.

What graphics plugins are you testing this with in mupen64plus-libretro? An does the animation actually show up? Or does it just skip the animation and show the pause menu?

**Comment by orbea** [comment]
I've tested better and its only fast with glide64 and angrylion in mupen64plus-libretro where it does show the animation. With gln64 and rice its just as slow, skips the animation and has other issues.

**Comment by loganmc10** [comment]
This is a confirmed issue. The menu is very slow in GLupeN64 and it is quite fast in mupen64plus+GLideN64. I've attached an apitrace for me to look at later when I have time.

[retroarch.trace.gz](https://github.com/loganmc10/GLupeN64/files/455724/retroarch.trace.gz)

**Comment by fzurita** [comment]
For the menu to show quickly, you need ”Copy color to RDRAM” enabled in GLideN64. GLideN64 used a hack for this that is only enabled when ”Copy color top RDRAM” is enabled.

**Comment by loganmc10** [comment]
It should be enabled by default on desktops (async), but it is still slow there, something must not be working right

**Comment by fzurita** [comment]
The hack is enabled by looking at the ROM header. Is that game detection and hack selection code still getting executed?

**Comment by loganmc10** [comment]
It's probably something messed up with the hack selection/detection stuff. The config setup for GLideN64 is customized to work with RetroArch but I probably need to look into how the hacks work

**Comment by loganmc10** [comment]
Ya the hack settings were being wiped out by the configuration settings.

I don't have time to test right now, but @orbea it should possibly be fixed now (https://github.com/loganmc10/GLupeN64/commit/f5e257db4488501b622312af67148f34b8ec7600)

**Comment by orbea** [comment]
This is fixed here, thanks!
