### ISSUE TITLE
GLupeN64 fails to start due to RetroArch commit

### ISSUE THREAD

**Issue by orbea** [loganmc10/GLupeN64#39]
This seems to be more of a RetroArch issue than GLupeN64, but given it breaks GLupeN64 I figure its worth mentioning here as well.

With the recent RetroArch master GLupeN64 will immediately crash without any error messages or log. Git bisect reveals the below commit as the culprit.
```
$ git bisect bad
73a1cd4631ca10ca3833c8b050e083b999e44117 is the first bad commit
commit 73a1cd4631ca10ca3833c8b050e083b999e44117
Author: mudlord <mudlord@mail.com>
Date:   Tue Sep 6 15:42:16 2016 +1000

    greatly optimized modern vertex shader for ribbon.

:040000 040000 2ef14c0aedcc14c8e68fd8316a1133e1fa211e00 60929693de0c2b3dfec6a8cac9cc69bb2d1ce497 M	gfx
```
https://github.com/libretro/RetroArch/commit/73a1cd4631ca10ca3833c8b050e083b999e44117

**Comment by loganmc10** [comment]
Thanks, I commented on the RetroArch issue explaining what the problem is.

**Comment by orbea** [comment]
mudlord fixed this.
https://github.com/libretro/RetroArch/pull/3531/commits/f3a0d8518eba3ef18f3f8b44249655414cecf403
