### ISSUE TITLE
Conker's Bad Fur Day Graphical Glitches

### ISSUE THREAD

**Issue by orbea** [loganmc10/GLupeN64#53]
OS: `Slakware64-current`
`RetroArch-2016.09.11_ebeb081_master-x86_64-1_git1`
`GLupeN64-2016.09.13_6d58b08_master-x86_64-1_git`

I've noticed two small graphical glitches in this game.

1. During some cut-scenes it changes to first person for a moment, this happens twice during the opening. When it does this it will display garbage at the bottom of the screen until it changes to 3rd person again.

![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/Conker's%20Bad%20Fur%20Day%20%28USA%29-160913-191045.png)

Apitrace - http://ks392457.kimsufi.com/orbea/stuff/trace/libretro/Conkers_Bad_Fur_Day_1.trace.xz

------------------------

2. When pausing the game with the start button it will render a blur effect, this works well except it cause the right side of the screen to flicker. This will continue until you move to a different game area or load a save state. This does not show well in a screenshot, but if tested by loading a save state instead of sram it will produce garbage on both the left and right sides of the screen similar to the first picture.

![2](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/Conker's%20Bad%20Fur%20Day%20%28USA%29-160913-192750.png)

Apitrace - http://ks392457.kimsufi.com/orbea/stuff/trace/libretro/Conkers_Bad_Fur_Day_2.trace.xz

This can also be reproduced by toggling fullscreen with the `f` key.

**Comment by loganmc10** [comment]
I can almost guarantee this is a problem with GLideN64 (it is notorious for weird graphics around the edges) but I'll take a look.

**Comment by orbea** [comment]
Thanks, if that is the case I will create a new issue for the GLideN64 repo for this, I will proceed under the assumption that GLupeN64 is a valid program for testing GLideN64. :)

**Comment by loganmc10** [comment]
Ya I could reproduce this in GLupeN64 and mupen64plus+GLideN64 (here is a screenshot from mupen64plus):

![conkers](https://cloud.githubusercontent.com/assets/848146/18520071/802e2a66-7a63-11e6-8512-3211fa48e8b9.png)

By the way, it looks like this issue was reported about a year ago to GLideN64 but the person that reported it said it was fixed now:
https://github.com/gonetz/GLideN64/issues/508

**Comment by orbea** [comment]
I moved the relevant bits to that issue, since this is an GLideN64 issue I will close this.
