### ISSUE TITLE
Changing Controller Pak without restarting

### ISSUE THREAD

**Issue by orbea** [loganmc10/GLupeN64#54]
Would it be possible to change the controller pak in game without restarting GLupeN64? So far it does not seem to support this.

Some games seem to expect this, for example `Beetle Adventure Racing` which will not allow saving if the game does not start with a `memory pak`, but before starting a race it asks if you wish to insert a `rumble pak`.

![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/Beetle%20Adventure%20Racing!%20(USA)%20(En,Fr,De)-160913-193919.png)
![2](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/Beetle%20Adventure%20Racing!%20(USA)%20(En,Fr,De)-160913-194021.png)

This can be tested in Orcarina of Time which will trigger the rumble when loading a saved game.

**Comment by loganmc10** [comment]
Is this something that works in mupen64plus-libretro?

**Comment by orbea** [comment]
Actually now that I tried it does. I can start Orcarina of Time with a `Memory Pak`, proceed to the title screen, change to the `Rumble Pak` and have my gamepad rumble when loading a game.

On the other hand `Beetle Adventure Racing` is far more playable with GlupeN64 than mupen64plus-libretro.

**Comment by loganmc10** [comment]
Ok I haven't tested it but 19b2c024340b213b210e3c314f9c67f05d5979d5 should fix this, it should work just like it does in mupen64plus-libretro

**Comment by orbea** [comment]
I have tested this, it works as well as mupen64plus-libretro with Orcarina of Time. 

With Beetle Adventure Racing it appears to work as it will complain about removing the rumble pak after the race to be allowed to save, but then wont let me save when I change back to a memory pak. I'm not really sure if this is a game bug or an emulation bug. Another problem is that I do not know when the game is supposed to trigger the rumble so I'm not sure if it works with this game.

Either way the initial issue is resolved so I will close this, thanks!
