### ISSUE TITLE
majora's mask cut scenes and intro black

### ISSUE THREAD

**Issue by epayson85** [loganmc10/GLupeN64#57]
Just about any cut scene so far is black.  You can hear everything but can't see anything.  First one is when the game starts and is supposed to show majora's mask fly in but its all black.

**Comment by loganmc10** [comment]
You need to enable framebuffer emulation

It is disabled by default on Android because it can hurt performance

**Comment by orbea** [comment]
Here is an older issue with more information.
https://github.com/loganmc10/GLupeN64/issues/14

**Comment by loganmc10** [comment]
The core option you need to enable is called ```glupen64-EnableFBEmulation```
