### ISSUE TITLE
Latest GLupeN64 (Windows) is practically broken

### ISSUE THREAD

**Issue by SigmaVirus** [loganmc10/GLupeN64#58]
Got some bad news and some good news.

The good news is that all my prior issues with GLupeN64 that I once reported is gone, the bad news is that I can't even play one single game.

All I get is a black screen with occasional garbled graphics from the game with working sound and controls.
Doesn't seem to matter which game I choose either, the described above is the only outcome for me.

Again, these are the games I own:

007 - GoldenEeye (Europe)
DOOM 64 (Europe)
Legend of Zelda, The - Majora's Mask (Europe)
Legend of Zelda, The - Ocarina of Time - Master Quest (Europe)
Legend of Zelda, The - Ocarina of Time (Europe)
Mario Kart 64 (Europe)
Paper Mario (Europe)
Perfect Dark (Europe)
Star Wars - Shadows of the Empire (Europe)
Super Mario 64 (Europe)
Super Smash Bros (Europe)
Yoshi's Story (Europe)

Haven't changed anything settings wise since the initial Windows support and made sure now that there hadn't been any new core settings added.

The things I have tried at the moment is to turn off shaders and VSync but it didn't made any difference.

Can't really upload anything helpful either I'm afraid, it is what it is.

I'm using the latest core from the 16th of September.

**Comment by loganmc10** [comment]
Does anyone else have this issue? I just tested a few games on Windows using the latest build and it all seems to work fine for me.

**Comment by ntelalis** [comment]
Works fine here on Windows 10 (GTX960)

**Comment by SigmaVirus** [comment]
OK, that's really weird then.

I came back from my vacation today and the only thing I did was to download the latest built GLupeN64 core and replace the very first built Windows version core with nothing else changed.

The first Windows version core works but have all those issues I reported, fullscreen crash, Yoshi's Story broken etc.

Something must have happened between now and then?

These are my specs and they're the same as a week ago:
i7 4790K @ 4.0GHz
AMD R9 380X 4GB GDDR5 (Crimson 16.3.2)
16GB Corsair XMS3 DDR3
Windows 10 Anniversary Update RS1 x64

What else can I do here?

**Comment by loganmc10** [comment]
You could try deleting your retroarch.cfg and retroarch-core-options.cfg?

What version of RetroArch do you use?

**Comment by SigmaVirus** [comment]
Well I don't know if this is a problem or not but I'm currently using a older version of RetroArch (1.3.0) which works great with this front-end:
https://github.com/phexe/RAEM

It works perfectly with every core I have today, even with the newer Mednafen Saturn core and I like RAEM because it looks like a Windows application and it makes RetroArch super easy for me to configure.

Every core I have in RetroArch today have separate RAEM instances (even Gambatte for GB and GBC), which makes it possible to have it more and behave like stand-alone emulators.

I like this kind of setup, but I have a feeling that this particular error will have to make me upgrade to a newer version of RetroArch.

I can try delete the config files though and see what happens.

BTW, how come GLupeN64 doesn't have a .info file? They seem to be important for every other core.

**Comment by loganmc10** [comment]
Ya I would try it with RetroArch 1.3.6 and a fresh config.

The .info file is just used to make it look "pretty" in the RetroArch Online Updater, it's not important

**Comment by SigmaVirus** [comment]
OK, I'll report back as soon as I have tried this and then we'll take it from there if the issue still persists.
Thanks for your support!

**Comment by SigmaVirus** [comment]
Well, a newer version of RetroArch did the trick!

Unfortunately were RAEM incompatible with the newer version of RetroArch so I'll have to find another suitable front-end for GLupeN64 or make a nice .bat file or something.

Thanks a lot again!

**Comment by SigmaVirus** [comment]
Although unnecessary and pointless at this point, I just want to tell you that I made a nice .bat file to launch my games through the new RetroArch version and it's working perfectly with GLupeN64.

Had to switch my S-Video shader from cgp to glslt though but I fixed that too.

@loganmc10, I owe you man! I can now retire Project64 after all these years and only use GLupeN64 as my sole N64 emulator.

BTW, I think it would be wise to suggest users on the front page to use newer versions of RetroArch for use of GLupeN64 at least.

**Comment by loganmc10** [comment]
I'll do a bit of testing and see if there is a "minimum version" of RetroArch that is needed across all platforms. If there is I'll put a note mentioning that, but I think using the latest version of whatever piece of software is a good practice anytime and not really specific to this project.

I'm glad you've got it working though, happy gaming!

**Comment by loganmc10** [comment]
v1.3.4 is the first version I can get working on Windows, so I'll mark that as the minimum version.
