### ISSUE TITLE
Link's Sub-Screen portrait broken (OoT and OoT MQ) in newer versions of GLupeN64

### ISSUE THREAD

**Issue by SigmaVirus** [loganmc10/GLupeN64#60]
@loganmc10 
I'm sorry if this is the wrong place to put this issue but I'm uncertain where to put it.

Anyway this is my issue:

GlupeN64 2016-09-16 (working)
![working](https://cloud.githubusercontent.com/assets/14175085/18807661/5648c3a4-824d-11e6-8967-40b2837fbfb7.png)

GLupeN64 2016-09-24 (non-working)
![non-working](https://cloud.githubusercontent.com/assets/14175085/18807665/684b3d2a-824d-11e6-8aed-d875572e954d.png)

I have a feeling this might be GLideN64 related and that's why I'm uncertain.

**Comment by orbea** [comment]
This is a little different for me and might be a GLideN64 issue.
```
$ git bisect good
7316e6795ef06d60494236c5d5f8f323a550f70c is the first bad commit
commit 7316e6795ef06d60494236c5d5f8f323a550f70c
Author: Logan McNaughton <logan@bacoosta.com>
Date:   Mon Sep 19 07:26:45 2016 -0700

    Update libretro-common and GLideN64

:100644 100644 b6a192a4bb805ad7fb6453aa5cba4be9ad88abee d20c74810c4093a58524e28e2a1509f49d14f42f M	.travis.yml
:040000 040000 0bf80a9aa57742888c0fe3f7ffcb6f5a502b71d2 2e17014371fa13e1cc5d9d0acac772abb5ddfe43 M	GLideN64
:040000 040000 0fa6d857b40d8f0395da0478284d0bbee172a8cd abc0967f0a9160523989a2948758dd8c3d7bd106 M	libretro-common
```
![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/2016-09-24-065846_1680x1050_scrot.png)

**Comment by loganmc10** [comment]
I see the same thing on Android, I'll make sure it's also happening in mupen64plus and then I'll file an upstream issue

**Comment by loganmc10** [comment]
Reproduced in mupen64plus, I filed an upstream issue: https://github.com/gonetz/GLideN64/issues/1134

I'll leave this open until it is sorted out.

**Comment by SigmaVirus** [comment]
Thanks @loganmc10

**Comment by orbea** [comment]
Better fixed by gonetz in https://github.com/gonetz/GLideN64/commit/f426d6188106d74b710883a49c0cc54322858c32.

**Comment by SigmaVirus** [comment]
Yep!
