### ISSUE TITLE
Saves no longer work

### ISSUE THREAD

**Issue by orbea** [loganmc10/GLupeN64#61]
OS: `Slackware64-current`
`RetroArch-2016.09.23_75f8a53_master-x86_64-1_git`
`GLupeN64-2016.09.23_f1fc759_master-x86_64-1_git`

Last working version: `GLupeN64-2016.09.15_6baff60_master-x86_64-1_git`

Saves that were created with GLupeN64 now no longer work, but if I downgrade to a previously working package the saves will work again. I can understand if sram compatibility between mupen64plus-libretro and GLupeN64 is broken, but saves within one emulator should just work regardless. This was tested with Orcarina of TIme.
```
$ git bisect bad
cab558dc5ee27e230295e2ebce87988e380b39f5 is the first bad commit
commit cab558dc5ee27e230295e2ebce87988e380b39f5
Author: Logan McNaughton <loganmc10@users.noreply.github.com>
Date:   Mon Sep 19 15:17:40 2016 -0600

    Show GL version in core name

:040000 040000 3fa4298238c1b49fa4f883214fee54923ded3b35 e5052938aa88c0edfdf4a45cef7d088da39b6ada M	libretro
```
https://github.com/loganmc10/GLupeN64/commit/cab558dc5ee27e230295e2ebce87988e380b39f5

Broken save - http://ks392457.kimsufi.com/orbea/stuff/games/retroarch/saves/GLupeN64/Zelda%20OoT%2064.srm

Related issue - https://github.com/loganmc10/GLupeN64/issues/50

**Comment by loganmc10** [comment]
Hi interesting, I guess the core name matters? I'll revert that change when I get a chance, sorry about that

**Comment by orbea** [comment]
Actually it was just beacause the save file folder changed from `GLupeN64` to `GLupeN64 OpenGL`, moving the saves to the new folder allows them to work again. I will close this...

**Comment by loganmc10** [comment]
Don't the saves just go in the same folder as the ROM? Or do you have it setup different?

**Comment by loganmc10** [comment]
I'll keep this then, it's nice to see what GL version is being used (for me at least)

**Comment by orbea** [comment]
I specify a save directory in RetroArch and then set it up so that the saves will go in Core Specific directories with the option `Sort Saves in Folders`.
