### ISSUE TITLE
(GLES2) Toy Story 2 - Coins render incorrectly

### ISSUE THREAD

**Issue by orbea** [loganmc10/GLupeN64#64]
OS: `Slackware64-current`
`mesa-2016.09.23_85e9bbc_master-x86_64-1_git`
`RetroArch-2016.09.27_5d209d0_master-x86_64-1_git`
`GLupeN64-2016.09.26_a661b3e_master-x86_64-1_git`

When playing Toy Story 2 coins which are all over the first level will render correctly at first and then sooner or later render incorrectly. This only occurs with GLES2 and does not affect GLES3 or OpenGL.

apitrace - http://ks392457.kimsufi.com/orbea/stuff/trace/libretro/glupen64_toy_story_2_egl.trace.xz

![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/Toy%20Story%202%20(E)%20%5b!%5d-160926-180935.png)

**Comment by orbea** [comment]
I can reproduce this on my intel thinkpad t420 with `apitrace replay`.

**Comment by loganmc10** [comment]
I played this for a few minutes on my phone and didn't see this issue, try it on desktop GLES2 tomorrow. Can you try wiping/resetting the core options and trying it?

apitrace replay is meant to be a faithful reproduction of what happened, so the fact that it happens on another machine doesn't mean the same issue would happen the same way on that machine(as far as I understand it)

**Comment by orbea** [comment]
I can't reproduce this on mupen64plus-libretro with any of the graphics plugins, `FORCE_GLES=1`, `GLIDEN64=1` or `GLIDEN64ES=1`.

I thought apitrace should be a good way to determine if an issue is related to the video driver or not, at least it gets often used this way to help debug nouveau. It doesn't always seem to work out that way depending on the program however. In the past this has worked out with GLupeN64 when a apitrace made on my desktop revealed a black screen on my laptop which was fixed by updating mesa.

**Comment by loganmc10** [comment]
Ya I guess the apitrace replay is executed by whatever the local drivver is so it would be s good way to find driver issues

**Comment by orbea** [comment]
Some more clues.
* This does not happen if framebuffer emulation is off.
* Destroying an enemy seems to trigger it.

**Comment by loganmc10** [comment]
I played through the whole level on my Android phone this morning and I didn't run into this. I'll test out GLES2 on my laptop tonight (intel mesa graphics).

**Comment by orbea** [comment]
I tried playing this in my intel thinkpad with GLES2 and was able to reproduce immediately after killing the first enemy. However only with GLES2 and not OpenGL. Potentially this is related to the GLES2 mesa driver if it is not reproducible on android?

**Comment by loganmc10** [comment]
Ya maybe, do you know of a way to get the keyboard keys to control analog input in RetroArch? The computer I have access to right now doesn't have a gamepad, so I only have a keyboard but can't really test because I can't move around.

**Comment by loganmc10** [comment]
I did test it using mupen64plus + GLideN64 in GLES2 mode (inside VMware with mesa graphics) and I couldn't reproduce it.

I have a Thinkpad T520 at home so hopefully I can reproduce it there.

**Comment by loganmc10** [comment]
Can you try and remove these lines:

https://github.com/loganmc10/GLupeN64/blob/master/custom/glsm/glsm.c#L252-L253

from custom/glsm/glsm.c and see if there is any difference?

**Comment by orbea** [comment]
Unfortunately I don't, I have the same problem with my laptop where the kernel does not recognize my xbox 360 controller, I haven't looked into it yet as the xpad driver should work. The input menu also didn't show any analog sticks. However I was still able to reproduce it by simply pressing z to fire in the first level where autoaim did the rest for me and the single coin visible from the start point started rendering incorrectly as soon as the first enemy was destroyed.

**Comment by orbea** [comment]
I tried removing lines 252 and 253 below and was still able to reproduce it.
```
   //This is a fix for https://github.com/loganmc10/GLupeN64/issues/13
glPixelStorei(GL_UNPACK_ALIGNMENT,1);
```

**Comment by loganmc10** [comment]
Ya I don't get it in VMware mesa when I shot the first enemy.

I suppose there is the possibility this is an issue with Mesa git? You run a pretty recent version of mesa don't you? Are you able to test with a stable version like 12.0.3?

**Comment by orbea** [comment]
I have mesa-12.0.1 in my laptop so if its a mesa issue its probably not new.

**Comment by loganmc10** [comment]
hm interesting, anyway I'll try this on my laptop tonight, it's a Thinkpad T520 with Fedora (Intel Mesa)

**Comment by fzurita** [comment]
This looks a lot like a driver bug. I bet the coin is texture mirroring and somehow that's not working correctly under some circumstances....

**Comment by orbea** [comment]
I asked in #dri-devel @ freenode. This is what they had to say.
```
11:02 <+anholt> orbea: I see a lot of GL_INVALID_OPERATION being thrown, suggesting the app is making bad GL calls.
11:03 <Kayden> yeah, that seems pretty sketchy
11:04 <Kayden> also the invalid operations seem to happen right about when things go awry
11:04 <+anholt> glUniform2f(12, ...) on a shader with 1 uniform.
11:05 <Kayden> Also, I can reproduce the problem with llvmpipe
```
Here is the apitrace output - http://pastebin.com/cJztYfew

**Comment by loganmc10** [comment]
So, I tested this inside VMware and I get those same GL errors, but the rendering doesn't get messed up. Also, I get the same errors using mupen64plus+GLideN64.

So basically it seems like there is an error happening (with GLideN64, not specific to glupen), but for some reason some drivers can safely "ignore" it, whereas some get messed up.

@orbea if you are able, I'd be curious if you could test this with mupen64plus + GLideN64 in GLES2 mode (you compile mupen64plus-core like ```make USE_GLES=1 -j4 all```) and you compile GLideN64 using something like ```cmake -DVEC4_OPT=On -DNOHQ=On -DMUPENPLUSAPI=On -DGLES2=On ../../src/```. If you can't do that that's ok, mupen64plus is kind of a pain to compile.

**Comment by loganmc10** [comment]
@orbea Can you try this and see if it fixes it?
Add:
```
glUseProgram(_pCombiner->m_program);
```
to this line:

https://github.com/loganmc10/GLupeN64/blob/master/GLideN64/src/GLUniforms/UniformSet.cpp#L133

**Comment by orbea** [comment]
That fixed it!

I tried testing this with mupen64plus + GLideN64, but I couldn't figure out how to configure their stupid mupen64plus-input-sdl plugin to do anything with either my keyboard or mouse... RetroArch is so much easier.

**Comment by loganmc10** [comment]
ok great, pull request has been submitted.

**Comment by orbea** [comment]
For future use I finally got mupen64plus to work, I can reproduce this issue in upstream GLideN64 without GLupeN64.

**Comment by loganmc10** [comment]
gonetz pushed a commit with a more thorough fix to this problem, I've updated GLupeN64 with that commit (5476ed320bc5163bee2e9804e6056f4397e7cd13) @orbea can you test and let me know if this issue is resolved for you?

**Comment by orbea** [comment]
Yes, its fixed with both GLupeN64 and GLideN64 for me.
