### ISSUE TITLE
Bringing over .htc custom texture pack support from upstream GLideN64

### ISSUE THREAD

**Issue by cascardian** [loganmc10/GLupeN64#65]
I envision this a core option where you can set up a path for the .htc files (currently %APPDATA%/Mupen64Plus/cache via base m64p) and a separate path for the texture-images-to-.htc conversion function (%APPDATA%/Mupen64Plus/hires_texture).

The usual options necessary to make some texture packs work (Full Alpha Channel usage, Alternate CRC etc.) would probably also be needed.

I don't believe custom texture pack support of any kind is currently in libretro. I don't know whether that (or GLideN64 integration, for that matter) is currently planned by the devs, so it would probably nicely distinguish this core for now--even if it were planned to eventually have everything merged in mupen64plus-libretro itself.

**Comment by loganmc10** [comment]
To be honest I've never been much of a believer in custom texture packs, I think the role of an emulator should be to emulate.

But my personal feelings aside, I don't mind if someone submits a pull request with this feature added, but I don't plan on spending any time on it myself.

Also, there is no plan to merge GLupeN64 with mupen64plus-libretro, they will stay separate.

**Comment by loganmc10** [comment]
I've started working on this in the "hirestex" branch.

I don't want to "over-stuff" the core options, I was thinking of including these options for this feature:

txFilterMode
txEnhancementMode
txHiresEnable

The path will be hardcoded to ```%RETROARCH_SYSTEM_DIR%/GLupeN64/hires_texture```

Does that sound like a decent implementation? is there anything I'm missing?

**Comment by loganmc10** [comment]
Ok everything should be working now, you can get a 64-bit Windows build with this feature here:

https://drive.google.com/file/d/0B8iAuv3fmhb_Si1nX3JSSllGTkE/view?usp=sharing

Let me know how things work, I tried a few of the texture filtering settings and I didn't see very much of a difference, although my testing was quite brief. The hi res textures go in this folder like I mentioned:

%RETROARCH_SYSTEM_DIR%/GLupeN64/hires_texture

The cached textures will end up here:

%RETROARCH_SYSTEM_DIR%/GLupeN64/cache

**Comment by loganmc10** [comment]
Probably just easier to let people test it in master, this has been implemented by: 033df1521ea9f97e148c8497d01e3a9578d83710
