### ISSUE TITLE
Wonder Project J2 - EnableNativeResTexrects causes white bars

### ISSUE THREAD

**Issue by orbea** [loganmc10/GLupeN64#66]
OS: `Slackware64-current`
`GLideN64-2016.09.27_d5412d3_master-x86_64-1_git`
`RetroArch-2016.09.27_ef99754_master-x86_64-1_git`
`GLupeN64-2016.09.28_30d3209_master-x86_64-1_git`

The start menu in the game `Wonder Project J2` will have large white bars with `Render 2D texrects in native resolution` in GLupeN64. However `EnableNativeResTexrects` in GLideN64 does not have this problem. The memorypak will need to be enabled for this game.

Apitrace - http://ks392457.kimsufi.com/orbea/stuff/trace/libretro/glupen64_Wonder_Project_J2.trace.xz
Apitrace log - http://pastebin.com/GdVrxgAa

__GLupeN64 + Render 2D texrects in native resolution__
![glupen64_EnableNativeResTexrects](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/EnableNativeResTexrects_GLupeN64_2016-09-28.png)
__mupen64plus + rsp-hle + GLideN64 + EnableNativeResTexrects__
![gliden64](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/EnableNativeResTexrects_mupen64plus_rsp-hle_video-gliden64_2016-09-28.png)
__GLupeN64__
![glupen64](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/GLupeN64_Wonder-Project-J2_2016-09-28.png)

**Comment by orbea** [comment]
This is not affected by frame buffer emulation.

**Comment by loganmc10** [comment]
Thanks for finding this, this was actually a problem with my VBO implementation, the 1 way this project differs from upstream GLideN64 (in order to work around the Linux Mesa issues).

Should be fixed in 39cb319f907bd779e661153b77815d9b2496a263

**Comment by orbea** [comment]
Yes, its fixed here. Thanks!
