### ISSUE TITLE
Discussion: resolutions

### ISSUE THREAD

**Issue by loganmc10** [loganmc10/GLupeN64#67]
I grabbed the preset resolution options from mupen64plus-libretro, I'm wanting to improve it a bit:

I was thinking of just having these 4 options:

320x240, 640x480, 960x720, 1280x960

And then adding an option to let the user choose between 4:3 and 16:9. GLideN64 has a widescreen hack so it looks better than just a straight up stretch.

The idea being that the person could choose one of those resolutions, and if they chose 16:9 it would convert it, like:

320x180, 640x360, 960x540, 1280x720

Thoughts? I'm curious to hear from some of the users on this

**Comment by SigmaVirus** [comment]
Well I can only speak for myself here but I'm trying to come as close to the original console output as possible so therefore I usually stick with 320x240 & 640x480 and 4:3, then I slap on a NTSC S-Video shader to get the final touch.

So basically, I'm striving for the most authentic experience as possible.
However some people don't care for that and will definitely have use for the higher resolutions with 16:9 and such.

**Comment by loganmc10** [comment]
Ok well I went ahead with this here:

https://github.com/loganmc10/GLupeN64/commit/cf959116cf66c18222519d83d48fc6217d7d1cef

Now you can choose 4:3 or 16:9 (4:3 being the default), if you choose 16:9 the core will attempt to render things without stretching them as described here:

http://gliden64.blogspot.de/2014/12/widescreen-hack_1.html

**Comment by SigmaVirus** [comment]
@loganmc10 
Looks good to me, nice work!

**Comment by alondero** [comment]
Any reason for limiting to just 1280x720? I have a 4k monitor and whilst I'd love to make the move from PJ64 to GlupeN64 the sharpness just isn't there (also not sure if shader support really works either as the xBRZ Texture Enhancement options really make textures sharp in PJ64 compared with Retroarch's shader options)

**Comment by loganmc10** [comment]
You can manually edit retroarch-core-options.cfg and put any value for "glupen64-169screensize" that you'd like (you also need to set "glupen64-aspect" to "16:9" to use the widescreen resolution).

I just didn't want a never ending list of resolutions in the core options that people had to scroll through.

> also not sure if shader support really works either

I'm not sure what you mean? RetroArch shaders are supported.

**Comment by dankcushions** [comment]
@loganmc10 might be cool to have a 'Display Resolution' or something option, which uses the resolution of the client itself?

**Comment by loganmc10** [comment]
@dankcushions that's not a bad idea. Is there some sort of way to query that information from RetroArch? I'm not aware of a really good cross-platform way to get that information.

Also @alondero I guess I was wrong, I was under the impression that RetroArch would let you put whatever value you want in retroarch-core-options.cfg but it seems to overwrite it with the default value if you enter something else. I guess I'll have to add some higher resolutions.

**Comment by loganmc10** [comment]
65cb737822e7ba023b963492e948462f50490682

**Comment by alondero** [comment]
@loganmc10 Yeah, just tried it myself - reverted back to 320x180. With the shaders, I'm just seemingly struggling to get the textures (such as text) to be as sharp as I can get it on PJ64. I'm using xBRZ Texture Enhancement 3x on PJ64 and one of the xbr shaders (XBR-Lv2-Fast) 3x on Retroarch and there is a noticeable difference in text quality (once I've got a comparable resolution I'll take a shot from each to show what I mean :-)

Great work on getting the patch for the higher resolutions in asap (I suspect you may get 2k monitor peeps wanting a 1440p option too - but I'm happy now at least ;-))

**Comment by loganmc10** [comment]
@alondero I can't add every conceivable resolution that might exist, unless there is some way to implement @dankcushions idea of a "Display Resolution" option, some people are going to have to suffer through playing N64 games at 1080p.... ;)

As far as the shaders go, there is probably not much I can do about that, shaders are a RetroArch feature, and there is nothing I can do to modify them at all from this project. If you compare PJ64 without shaders and GLupeN64 without shaders, and they look the same, then you'd have to talk to the RetroArch people about that.

**Comment by dankcushions** [comment]
> @dankcushions that's not a bad idea. Is there some sort of way to query that information from RetroArch? I'm not aware of a really good cross-platform way to get that information.

i have a feeling i tried this before and failed. yeah, just checked on IRC and this isn't possible right now. i think as we get more GL (etc) 3d cores, it starts to make more sense to have way for a core to just use all the resolution available to it. provoked some discussion, at least :)

**Comment by loganmc10** [comment]
@dankcushions Ya RetroArch is already doing this (https://github.com/libretro/RetroArch/blob/master/gfx/drivers/gl.c#L1876) there just isn't a way to pass that info along to the core right now.
