### ISSUE TITLE
Shadows in Mario 64 are flickering after toggling fullscreen (Linux)

### ISSUE THREAD

**Issue by loganmc10** [loganmc10/GLupeN64#69]
I just noticed that the shadows in Mario 64 are flickering, at least on desktop Linux. This doesn't happen in mupen64plus+GLideN64. I don't have time to test now so I'm leaving this here to remind me

**Comment by SigmaVirus** [comment]
OK, what about Windows does it occur there too? I don't recall this happens on Windows at all.

**Comment by loganmc10** [comment]
hm I just tried it this morning and I'm not seeing it, maybe my computer was having a bad night.. I'll re-open it if I see it again.

**Comment by orbea** [comment]
I've seen GLupeN64 produce several issues that vanished without explanation when trying to reproduce them...

**Comment by loganmc10** [comment]
It's like it knows lol it's got a mind of its own

**Comment by loganmc10** [comment]
Actually this seems to happen after toggling full screen

**Comment by loganmc10** [comment]
I just tried an old commit and it happened there too, so at least it's not something I did recently that broke it

**Comment by orbea** [comment]
I can reproduce this too so its not just you. After toggling full screen it will alternate between displaying a half circle shadow, flickering and entirely vanishing. Location in the game seems to play a role.

**Comment by loganmc10** [comment]
Ya it's very strange, I don't see any GL errors being generated, and it doesn't seem to happen in mupen64plus

**Comment by orbea** [comment]
I went to my first GLupeN64 package that didn't crash on full screen toggle and it still occurred there, so it went wrong before a93cbe0.

**Comment by SigmaVirus** [comment]
Well my rig is in molecule pieces right now so I can't test this out at the moment until I get the last parts so I can rebuild it but I'm almost certain I've never experienced this kind of thing with GLupeN64 on Windows.

How does it look? Can it be documented with pictures?

**Comment by loganmc10** [comment]
In Mario 64 just wandering outside the castle, the shadows will flicker or only half the shadow will show up (like the shadows under Mario or under the trees). It happens after toggling full screen

**Comment by orbea** [comment]
Apitrace is giving me some errors that may be related. I have also never seen apitrace create 3 windows when replaying something before. I wonder if that should happen?

Apitrace - http://ks392457.kimsufi.com/orbea/stuff/trace/libretro/GLupeN64_Super_Mario_shadows.trace.xz
Log - http://pastebin.com/NvTQBjT5

Here are some images.

![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/2016-10-05-101726_1680x1050_scrot.png)
![2](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/2016-10-05-101642_1680x1050_scrot.png)

**Comment by loganmc10** [comment]
I believe I fixed those glInvalidateFramebuffer errors with the commit I pushed today, is that apitrace from the latest commit?

**Comment by orbea** [comment]
Its with commit 8c8e237, so last one from yesterday.

**Comment by orbea** [comment]
I've tried the latest commit, the major api errors are indeed gone, but the warnings persist. They occur about when context_reset does. There are also a few screen resize errors that may be due to my 1689x1050 monitor resolution.

**Comment by SigmaVirus** [comment]
@loganmc10 and @orbea 
I think I know what you mean now, it's just that I never thought about it before.

By the way what resolution are you on? The reason I ask is because I usually run it on native resolution (320x240) and the reason I haven't noticed it might be of what resolution you're playing with.

Some things may be more apparent the higher the internal resolution is, I don't know.

**Comment by orbea** [comment]
I tested with entirely default settings and the native resolution. No difference.

**Comment by loganmc10** [comment]
The strange thing is that it happens even if you do this:

Open Mario 64, toggle full screen, then load a save state (I have one where he is just standing outside the castle). It still happens then!

**Comment by loganmc10** [comment]
@orbea you won't believe it, it doesn't happen on Windows...

**Comment by SigmaVirus** [comment]
So that's why I haven't noticed it, because it's not Windows related at all.

**Comment by orbea** [comment]
You've made it worse.

In commit https://github.com/loganmc10/GLupeN64/commit/335bf36fea7940015a89631e2b363b6f2b87a789 full screen toggle now does.
![3](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/2016-10-06-184224_1680x1050_scrot.png)

**Comment by orbea** [comment]
And commit rewritten https://github.com/loganmc10/GLupeN64/commit/335bf36fea7940015a89631e2b363b6f2b87a789 gets us back where we started. :)

**Comment by SigmaVirus** [comment]
Damn that doesn't look good at all, that's pretty scary actually. It's like Mario is getting obliviated.

**Comment by fzurita** [comment]
That shadow issue sounds exactly like the polygon offset bug in Android. See here: https://github.com/gonetz/GLideN64/blob/master/src/Config.h#L55

That is the workaround that GLideN64 implements for Android. I wonder if it would work with linux as well.

**Comment by loganmc10** [comment]
thanks for the hint @fzurita ! RetroArch/GLupeN64 has a pretty thorough GL state caching system (if it thinks glPolygonOffset(-3.0f,-3.0f) has already been set, it will ignore a call to set it again).

When toggling full screen, the OpenGL context is re-created, so glPolygonOffset gets reset to 0,0, but GLupeN64 thinks it's still set to -3,-3, so it ignores the call to set it to -3,-3.

Obviously on Windows it doesn't actually reset the value of glPolygonOffset when you re-create the context. I really wish all the different OpenGL implementations acted the same way....

**Comment by fzurita** [comment]
Cool

**Comment by orbea** [comment]
Great, its fixed here too. :)

**Comment by SigmaVirus** [comment]
Mario lives again!
