### ISSUE TITLE
Need to fix OpenGL shader caching

### ISSUE THREAD

**Issue by Awakened0** [loganmc10/GLupeN64#71]
I noticed an empty directory called C is being created in the root of my RetroArch folder every time this core is run now. No other cores do it. Must be a recent thing since my older build from Oct. 3rd doesn't do this.

I got a verbose log if it helps any: http://hastebin.com/emeqaqutey.py

**Comment by loganmc10** [comment]
Interesting, this is most likely related to shader storage being turned on. Normally, each time you run the core it compiles OpenGL shaders for the game you are playing. Basically now it does that the first time you play, then it saves a binary version of the shader to the hard drive so the next time you play the game it doesn't have to compile the shaders.

It's supposed to save them to %APPDATA%/roaming/Mupen64Plus or thereabouts, on Monday I'll look into why this C folder is being created

**Comment by Awakened0** [comment]
I see that directory was created as well. It's empty too, even after running several games. Wouldn't it be better to put that stuff in the System directory defined in RetroArch, since that's where cores usually store stuff?

**Comment by loganmc10** [comment]
Yes it would, @dankcushions I remember you explained to me once how to retrieve that info through the libretro api, can you fill me in again? I can't remember what the context was the last time you explained this to me.

**Comment by dankcushions** [comment]
Sure! Here's an example: https://github.com/libretro/mame2003-libretro/blob/master/src/libretro/libretro.c#L493

generally, savedir is used for user-updated files (.cfgs, saves, etc), and systemdir for everything not, so yeah systemdir seems appropriate here.

**Comment by Awakened0** [comment]
It doesn't create the C dir in RetroArch or the Mupen one in Roaming with the latest build. I'm assuming 38135d67ad4db350c6236e62a5d849ce1bac6c5e fixed it :)

**Comment by loganmc10** [comment]
Ya there is still something wrong with shader storage though. It should be saving binary shaders to the RetroArch system dir, I haven't had time to look into it yet

**Comment by Awakened0** [comment]
It's placing them in my "shaders" dir, which is kinda funny. That's where only cg or slang shaders should be :P

**Comment by loganmc10** [comment]
Thanks for the hint! It will only create the shaders if a folder called "shaders" exists inside the RetroArch system dir. I need to make it create a folder called "GLupeN64/shaders" or something and put them in there.

**Comment by loganmc10** [comment]
@Awakened0 can you try it now? It should create a "GLupeN64" folder now

**Comment by Awakened0** [comment]
It created a folder in my RetroArch folder called SystemGLupeN64 with a shaders folder inside that. So something is still off.

**Comment by loganmc10** [comment]
Ya it was missing a slash (/) in the path, should be fixed now

**Comment by Awakened0** [comment]
Seems to be working right now. For some reason the first time I ran the new build, it put a shader cache file in RetroArch\Shaders as well as RetroArch\System\Glupen64\shaders, but I haven't been able to reproduce that.

**Comment by loganmc10** [comment]
Ok I'm going to close this then, I've tested on Android and it's working the same there as well.
