### ISSUE TITLE
Feature Request: Document core options in GLupeN64.

### ISSUE THREAD

**Issue by orbea** [loganmc10/GLupeN64#73]
I noticed the core options were described in the wiki, could this be added to GLupeN64 so that it can be viewed from the RetroArch menu? RetroArch allows for options to have descriptions which can be viewed by the gamepad select button (Right shift on my keyboard), for example try `Load Core`. It would be helpful if this documentation existed inside GLupeN64 too especially since the documentation already exists.

https://github.com/loganmc10/GLupeN64/wiki

**Comment by loganmc10** [comment]
Do you have an example of a core that does this? I'm not aware of any way to do this

**Comment by orbea** [comment]
You're right, I'm not sure any do yet. If this is unpractical it can be closed. I will ask in the retroarch channel if there are such examples.

**Comment by orbea** [comment]
I guess this is only the RetroArch features and not the core options. I guess the wiki will have to do. This can be reopened if this is ever added to the libretro API.

**Comment by loganmc10** [comment]
It's a really good idea, but ya it seems like it would need a change to the API.
