### ISSUE TITLE
[Linux] Pokemon Snap

### ISSUE THREAD

**Issue by telanus** [loganmc10/GLupeN64#77]
Hi

Tried glupen64 and works better than mupen64 running pokemon snap, but it seems the game/core/retroarch stops responding to input as soon as you leave the lab to go take pictures. also on the option screen, the text is all white.

tested Mario kart 64 and it accepts all input (but have loads of missing graphics)

Running Ubuntu Mate 16.04.01

**Comment by loganmc10** [comment]
What video driver are you using? You may need to update Mesa on Ubuntu 16.04 to fix the graphics

You can enable this ppa to get the latest version of Mesa:

https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers

That should fix any missing graphics. Ill look into Pokemon snap

**Comment by loganmc10** [comment]
The white text in the options menu is probably also caused by Ubuntu 16.04's Mesa version. Basically there is a Mesa bug in the version currently used by Ubuntu 16.04, so you'll need to use that PPA or update Mesa in some other way for it to work.

As far as the input issues, I don't seem to have any issues. I believe in Pokemon Snap you'll need to enable "glupen64-EnableCopyAuxiliaryToRDRAM" (Copy auxiliary buffers to RDRAM) in the RetroArch core Options in order for it to recognize when you've "captured' a Pokemon

**Comment by telanus** [comment]
Hi

got the textures back :smile_cat: but still stuck with no input while "capturing" pokemon, the input works while in the lab :frowning_face:

**Comment by loganmc10** [comment]
Does anyone else have these issues? I can't seem to reproduce this

**Comment by loganmc10** [comment]
@telanus Can you try this branch:

https://github.com/loganmc10/GLupeN64/tree/cheats

mupen64plus implements a few hacks via cheats for this game, that branch should make cheats work with GLupeN64, so I'm curious if it helps with Pokemon Snap.

**Comment by loganmc10** [comment]
I've merged the cheat code into the main branch, so this should hopefully be fixed now

**Comment by telanus** [comment]
Hi. Hadn't have a lot of time to test the last few weeks due to RL stuff (esp work related), compiled the source this morning and nothing shows :( 

did a few hundred compiles :stuck_out_tongue_closed_eyes:  and seems https://github.com/loganmc10/GLupeN64/commit/68cb1bb58980570643b40172512e0f04dae6f961 breaks the display on my system, with https://github.com/loganmc10/GLupeN64/commit/b0ac029a7a482265688e61937782c59e4574f2d9 it compiles and display everything, with https://github.com/loganmc10/GLupeN64/commit/68cb1bb58980570643b40172512e0f04dae6f961 it shows nothing, but you can hear the music and input is accepted

**Comment by loganmc10** [comment]
What kind of graphics card do you have? Can you do a "glxinfo" and grep for "buffer_storage"?

**Comment by telanus** [comment]
I'm using a Nvidia GT240 with the latest mesa. added the output from glxinfo 
[txt.txt](https://github.com/loganmc10/GLupeN64/files/574995/txt.txt)

**Comment by loganmc10** [comment]
Hm ok I thought ARB_buffer_storage was available on pretty much all graphics cards but it looks like that is not the case, I'll have this fixed later today

**Comment by loganmc10** [comment]
Ok it should work now with the latest master

**Comment by telanus** [comment]
works great thanx :smile_cat: 

only problem with the game left is:
![screenshot at 2016-11-07 20-23-11](https://cloud.githubusercontent.com/assets/19357986/20070504/4884e49c-a529-11e6-9293-7b9473413539.png)

but that can wait, have seen that this game has way too many problems to be a priority :D
