### ISSUE TITLE
Rogue Squadron does not load!

### ISSUE THREAD

**Issue by jaburgeson** [loganmc10/GLupeN64#78]
Rogue Squadron does not load.

It just shows a black screen when the game launchers.

The gliden64.log file in the retroarch directory says

[GLideN64]: error - unknown ucode!!!

It works with the standard mupen core and it also works with Project64 using the GLideN64 plugin.

This is on Windows 10 using 64bit RetroArch.

**Comment by loganmc10** [comment]
You need to Sept the RSP mode to "LLE" in the core options

**Comment by jaburgeson** [comment]
I could of swore I tried this already, but you are right.  It is working now!

Thank you very much for your hard work.
