### ISSUE TITLE
CRC-related build issue with latest master via RetroPie + RPI3

### ISSUE THREAD

**Issue by dankcushions** [loganmc10/GLupeN64#79]
here's where it bombs out:
```
g++ -O3 -mcpu=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -funsafe-math-optimizations -pipe -std=c++11 -O3 -DNDEBUG  -DOS_LINUX -DHAVE_NEON -D__ARM_NEON__ -D__NEON_OPT -D__LIBRETRO__ -DM64P_PLUGIN_API -DM64P_CORE_PROTOTYPES -D_ENDUSER_RELEASE -DSINC_LOWER_QUALITY -DMUPENPLUSAPI -DTXFILTER_LIB -DUSE_DEPTH_RENDERBUFFER -D__VEC4_OPT -DGIT_VERSION=\""678c40c"\"  -I/opt/vc/include -I./custom -I./custom/mupen64plus-core -I./GLideN64/src -I./GLideN64/src/osal -I./mupen64plus-core/src -I./mupen64plus-core/src/api -I./custom/mupen64plus-core/plugin/audio_libretro -I./libretro-common/include -I./libretro -I./custom/GLideN64 -I./custom/glsl-optimizer -I./glsl-optimizer/src/glsl -I./glsl-optimizer/include -I./glsl-optimizer/src -I./glsl-optimizer/src/mesa  -fPIC  -DVC -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -mno-unaligned-access  -DHAVE_OPENGLES -DHAVE_OPENGLES2 -DGLES2  -DNEW_DYNAREC=3 -DDYNAREC -c GLideN64/src/CRC_ARMV8.cpp -o GLideN64/src/CRC_ARMV8.o
{standard input}: Assembler messages:
{standard input}:45: Error: selected processor does not support ARM mode `crc32w r3,r3,r4'
{standard input}:48: Error: selected processor does not support ARM mode `crc32w r3,r3,r4'
{standard input}:63: Error: selected processor does not support ARM mode `crc32h r3,r3,ip'
{standard input}:72: Error: selected processor does not support ARM mode `crc32w r3,r3,ip'
{standard input}:76: Error: selected processor does not support ARM mode `crc32b r3,r3,r2'
{standard input}:115: Error: selected processor does not support ARM mode `crc32h r3,r3,ip'
Makefile:283: recipe for target 'GLideN64/src/CRC_ARMV8.o' failed
make: *** [GLideN64/src/CRC_ARMV8.o] Error 1
make: *** Waiting for unfinished jobs....
Removing additional swap
```

**Comment by loganmc10** [comment]
It's because of the cflags that are set

```
-mcpu=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -funsafe-math-optimizations -pipe
```

Those are not set by GLupeN64, they are breaking it.

**Comment by dankcushions** [comment]
I believe retropie build scripts use a pre-baked set of compile params for each pi platform (eg, including the above for pi3). if i recall, the reason for this is because some emulators don't have build params for pis at all, and also it allows retropie to fix some build issues without having to PR or fork cores.

Given that this repo has specific build needs, and has pi-specific parameter options alreadyt, perhaps for the glupen script in retropie we could just clear out retropie's build variables and only pass the platform, as required: https://github.com/loganmc10/GLupeN64/blob/master/BUILDING.md#building-the-project. What do you think, @joolswills ?

(I'll close this issue as it's not this repo's problem!)

**Comment by joolswills** [comment]
We don't use those those options - do you have an out of date retropie-setup @dankcushions  ? this is something we have already resolved.

BTW this is actually a binutils issue as those compile options should suffice :-) it's been fixed upstream now

**Comment by loganmc10** [comment]
@gizmo98 might have some insight since he figured out how to do this fancy CRC stuff to begin with

**Comment by joolswills** [comment]
It's already resolved - see https://github.com/RetroPie/RetroPie-Setup/pull/1678

**Comment by joolswills** [comment]
sorry. wrong link.

**Comment by joolswills** [comment]
We discussed it here - https://github.com/RetroPie/RetroPie-Setup/pull/1675

**Comment by gizmo98** [comment]
@loganmc10 jools already fixed it. It was a binutils bug. If -mcpu=cortex-a53 is set compilation fails. @dankcushions do you use the latest RetroPie-Setup script or a custom configuration?

**Comment by dankcushions** [comment]
@joolswills I updated my script today but it can't have been before I tried this as I've just re-updated and it works now! Thanks :)
