### ISSUE TITLE
Broken camera in Majora's Mask

### ISSUE THREAD

**Issue by SigmaVirus** [loganmc10/GLupeN64#81]
Seems like the camera in Majora's Mask is broken:
![majora s mask](https://cloud.githubusercontent.com/assets/14175085/19509176/d0461ba4-95dd-11e6-8980-eb51a5ab9adc.png)

These are my settings for GLupeN64:
**glupen64-cpucore = "dynamic_recompiler"
glupen64-rspmode = "HLE"
glupen64-43screensize = "640x480"
glupen64-169screensize = "320x180"
glupen64-aspect = "4:3"
glupen64-BilinearMode = "3point"
glupen64-EnableFBEmulation = "True"
glupen64-UseNativeResolutionFactor = "0x"
glupen64-EnableCopyAuxiliaryToRDRAM = "False"
glupen64-EnableCopyColorToRDRAM = "Async"
glupen64-EnableCopyDepthToRDRAM = "FromMem"
glupen64-EnableCopyColorFromRDRAM = "False"
glupen64-EnableHWLighting = "False"
glupen64-CorrectTexrectCoords = "Off"
glupen64-EnableNativeResTexrects = "False"
glupen64-EnableLegacyBlending = "False"
glupen64-astick-deadzone = "15"
glupen64-pak1 = "none"
glupen64-pak2 = "none"
glupen64-pak3 = "none"
glupen64-pak4 = "none"**

I don't know when it got broken or what commit that broke it because it worked quite recently (a couple of weeks ago)

I have reported it to @gonetz at [GLideN64](https://github.com/gonetz/GLideN64/issues/1185) and he says he can't reproduce it on the desktop version.

So maybe this is GLupeN64 related after all.

**Comment by loganmc10** [comment]
Can you provide a save state?

**Comment by SigmaVirus** [comment]
Absolutely!
[Legend of Zelda, The - Majora's Mask (Europe).zip](https://github.com/loganmc10/GLupeN64/files/538964/Legend.of.Zelda.The.-.Majora.s.Mask.Europe.zip)

**Comment by loganmc10** [comment]
Should be fixed in the buildbot:

http://loganbuildbot.s3-website-us-east-1.amazonaws.com/

**Comment by SigmaVirus** [comment]
It's fixed, thanks a lot!
