### ISSUE TITLE
Perfect Dark crashes right at A51 - Infiltration level startup

### ISSUE THREAD

**Issue by SigmaVirus** [loganmc10/GLupeN64#83]
Just when I thought I finally got a stable build of GLupeN64 that seemed to pass all my tests this happens:
![pd](https://cloud.githubusercontent.com/assets/14175085/19559834/fcf493c0-96d1-11e6-9d99-aa97cedaf3eb.png)

I can reproduce this crash every time.

Here's a save file for the brave:
[Perfect Dark (Europe).zip](https://github.com/loganmc10/GLupeN64/files/541673/Perfect.Dark.Europe.zip)
 
I'm not sure what triggers this because most of the levels I tried starts up just fine.

**Comment by loganmc10** [comment]
Did it work in the past?

**Comment by SigmaVirus** [comment]
Yes, the oldest version of GLupeN64 I have is from 2016-09-16 (where it still says "GLupeN64 2.5" in the title) and it works perfectly there.
So something must have happened between then and now.

I think I have some newer ones that I can try out too, but I didn't update frequently.

**Comment by SigmaVirus** [comment]
Well this certainly is weird, I can't seem to reproduce it anymore even on the latest I have which crashed...
I need to start out fresh with my configuration files and try again just to make sure.

**Comment by SigmaVirus** [comment]
I'm closing this for now, I don't know what the hell happened back then because I can't reproduce this at all anymore.

I blame this on a space-time continuum glitch.
