### ISSUE TITLE
GLupeN64 Crashes On Latest RetroArch Nightlies [Windows]

### ISSUE THREAD

**Issue by Awakened0** [loganmc10/GLupeN64#87]
I made an issue report on this over on [RetroArch's git](https://github.com/libretro/RetroArch/issues/3843), but maybe it's more appropriate here. RA got some commits related to input recently and the GDB backtrace shows something about input:

> Program received signal SIGSEGV, Segmentation fault.
> 0x00000000004f7789 in dinput_is_pressed (di=0x4f6f110, binds=0x0, port=2, id=7)
> at input/drivers/dinput.c:282
> 282 input/drivers/dinput.c: No such file or directory.
> (gdb) bt
> #0 0x00000000004f7789 in dinput_is_pressed (di=0x4f6f110, binds=0x0, port=2, id=7)
> at input/drivers/dinput.c:282
> #1 0x00000000004f7e4e in dinput_input_state (data=0x4f6f110,
> binds=0x96de80 , port=2, device=1, idx=0, id=7)
> at input/drivers/dinput.c:489
> #2 0x000000000042a74e in input_state (port=2, device=1, idx=0, id=7) at input/input_driver.c:464
> #3 0x0000000000402443 in core_input_state_poll (port=2, device=1, idx=0, id=7) at core_impl.c:73
> #4 0x000000001224472a in inputGetKeys_default ()
> from F:\Blue\Emulation\Emulators\RetroArch\cores\glupen64_libretro.dll
> #5 0x0000000012244dc4 in egcvip_get_input ()
> from F:\Blue\Emulation\Emulators\RetroArch\cores\glupen64_libretro.dll
> #6 0x0000000012205315 in read_controller ()
> from F:\Blue\Emulation\Emulators\RetroArch\cores\glupen64_libretro.dll
> #7 0x0000000012205b8d in update_pif_read ()
> from F:\Blue\Emulation\Emulators\RetroArch\cores\glupen64_libretro.dll
> #8 0x0000000012205f25 in write_si_regs ()
> from F:\Blue\Emulation\Emulators\RetroArch\cores\glupen64_libretro.dll
> #9 0x0000000010678b7a in ?? ()
> Backtrace stopped: previous frame inner to this frame (corrupt stack?)

**Comment by loganmc10** [comment]
Does this happen with mupen64plus-libretro?

**Comment by Awakened0** [comment]
Yep, here's the backtrace:

> Program received signal SIGSEGV, Segmentation fault.
> 0x00000000004f7ec9 in dinput_is_pressed (di=0x5ef8100, binds=0x0, port=2, id=7)
>     at input/drivers/dinput.c:282
> 282     input/drivers/dinput.c: No such file or directory.
> (gdb) bt
> #0  0x00000000004f7ec9 in dinput_is_pressed (di=0x5ef8100, binds=0x0, port=2, id=7)
>     at input/drivers/dinput.c:282
> #1  0x00000000004f85a6 in dinput_input_state (data=0x5ef8100,
>     binds=0x96ef00 <libretro_input_binds>, port=2, device=1, idx=0, id=7)
>     at input/drivers/dinput.c:489
> #2  0x000000000042a503 in input_state (port=2, device=1, idx=0, id=7) at input/input_driver.c:457
> #3  0x0000000000402443 in core_input_state_poll (port=2, device=1, idx=0, id=7) at core_impl.c:73
> #4  0x00000000179f596a in inputGetKeys_default (Control=2, Keys=0x14b16050)
>     at mupen64plus-core/src/plugin/emulate_game_controller_via_libretro.c:710
> #5  0x00000000179f7814 in egcvip_get_input (opaque=<optimized out>)
>     at mupen64plus-core/src/plugin/emulate_game_controller_via_libretro.c:1040
> #6  0x000000001799f53e in game_controller_get_input (cont=0x183e2c00 <g_si+384>)
>     at mupen64plus-core/src/si/game_controller.c:185
> #7  read_controller_read_buttons (
>     cmd=0x183e2ab1 <g_si+49> "\001\004\001\377\377\377\377\377\001\004\001\377\377\377\377_",
>     cont=0x183e2c00 <g_si+384>) at mupen64plus-core/src/si/game_controller.c:58
> #8  read_controller (cont=cont@entry=0x183e2c00 <g_si+384>,
>     cmd=cmd@entry=0x183e2ab1 <g_si+49> "\001\004\001\377\377\377\377\377\001\004\001\377\377\377\377_") at mupen64plus-core/src/si/game_controller.c:214
> #9  0x000000001799ecca in update_pif_read (si=0x183e2a80 <g_si>)
>     at mupen64plus-core/src/si/pif.c:225
> #10 0x00000000179b6675 in dma_si_read (si=0x183e2a80 <g_si>)
>     at mupen64plus-core/src/si/si_controller.c:68
> #11 write_si_regs (opaque=0x183e2a80 <g_si>, address=<optimized out>, value=<optimized out>,
>     mask=<optimized out>) at mupen64plus-core/src/si/si_controller.c:122
> #12 0x000000002354dccf in ?? ()
> Backtrace stopped: previous frame inner to this frame (corrupt stack?)

I've found one game so far that doesn't run into the problem on either core; Banjo Kazooie.

**Comment by Awakened0** [comment]
Ok, I think this is more of a RetroArch issue than something with the N64 cores, since MAME, mednafen-supergrafx and Nestopia also crash. I've updated the issue on RetroArch's git and am closing this one.
