### ISSUE TITLE
Avoid using COHERENT mappings for apitrace's benefit

### ISSUE THREAD

**Issue by imirkin** [loganmc10/GLupeN64#88]
Unfortunately using a COHERENT mapping is incompatible with apitrace - since you can update a buffer at any time, it just gives up.

However you only update the vbo/ibo's in fairly controlled environments. Should be easy enough to stick  a glFlushMappedBufferRange in there for the range being updated. This should let you drop the coherent bit of the mapping while maintaining persistent mappings across draws.

**Comment by loganmc10** [comment]
I'll need to look into this. If I recall the Dolphin Emulator team had an issue with Adreno GPU's and GL_MAP_FLUSH_EXPLICIT_BIT/glFlushMappedBufferRange

**Comment by loganmc10** [comment]
I agree that having a broken apitrace isn't great. I think what I'll do is have it use glFlushMappedBufferRange when it is a debug build (DEBUG=1), since it seems like coherent mapping is the better/less overheard way to do it in general.

**Comment by loganmc10** [comment]
Ok this is delt with in https://github.com/loganmc10/GLupeN64/commit/027750b59f88d2a41afeab7987bc79d1e53fa1b9

If you build with DEBUG=1 then it will use glFlushMappedBufferRange instead of coherent mapping.

**Comment by imirkin** [comment]
Nice, thanks!
