### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by fr500** [loganmc10/GLupeN64#91]
As of today these are the build errors reported by the libretro buildbot:
emscripten http://hastebin.com/isarobusif
osx x64 http://hastebin.com/payenajexe
linux x86 http://hastebin.com/utuxayujok
android (gles3) https://bot.libretro.com/log/2016-11-04_glupen64_gles3_android-armv7.log

It's still going so I'll post more as it finishes

**Comment by loganmc10** [comment]
These all seem unrelated. Emscripten and OS X are not supported.

Linux x86 needs nasm installed

Android GLES3 needs a standalone tool chain with api >= 21 now (this is a recent requirement)

**Comment by fr500** [comment]
Oh but emscripten used to work! hard to mantain?
Ok I guess I'll build another toolchain for GLES3

**Comment by loganmc10** [comment]
Ya emscripten had problems, texture corruption, controller problems, performance problems. It complicated the code and didn't have very many users, so I got rid of it

**Comment by fr500** [comment]
Sad to hear, it works pretty well for me, at least for SM64, it's still included since I haven't done a git clean in the retroarch source tree

**Comment by fr500** [comment]
Glupen GLES3 builds now btw
