### ISSUE TITLE
Build failure with DEBUG=1

### ISSUE THREAD

**Issue by orbea** [loganmc10/GLupeN64#95]
OS: `Slackware64-current`
`gcc-5.4.0`

When building with `DEBUG=1` it will fail.

Build log - http://pastebin.com/Ap42JXES

**Comment by loganmc10** [comment]
Yes this is a result of the recently added high resolution texture code, which has some Windows specific stuff in it, I've submitted a pull request to GLideN64:

https://github.com/gonetz/GLideN64/pull/1223

**Comment by orbea** [comment]
Ah, thanks! I guess this can be closed after the result of your PR is clear. :)

**Comment by loganmc10** [comment]
Should be fixed by 786fb76bde54fd46b9908bb8824c99a899d39854

**Comment by orbea** [comment]
Yes. :)
